### PR TITLE
Rename assets

### PR DESCRIPTION
**Pull request by maxd-nordic**

### CODE REVIEW

**Review by coderbyheart — CHANGES_REQUESTED** [review]
Has commits from #32

**Comment by maxd-nordic** [comment]
> Has commits from #32

yes, because it depends on that.

**Comment by coderbyheart** [comment]
No, this PR should change the descriptions only.
Then the other PR can be rebase against saga and it will have the changes from this PR.

**Comment by coderbyheart** [comment]
I'll fix it.

**Pull request merged**
