### PR TITLE
feat: update to NCS 2.5

### LINKED ISSUE #25: Add build with latest changes
- sdk-nrf v2.5.x with
  - https://github.com/maxd-nordic/sdk-nrf/tree/atv2-ina3221
  - https://github.com/nrfconnect/sdk-nrf/pull/12784

### PR DESCRIPTION
**Pull request by maxd-nordic**
This also includes the GNSS name change.

Closes #25

### CODE REVIEW

**Comment by coderbyheart** [comment]
Adding the 2.5.0 tag here: https://github.com/NordicPlayground/nrf-docker/pull/86

**Comment by maxd-nordic** [comment]
not sure why the wifi shield is not found. it is present under this name in the repo.

**Comment by coderbyheart** [comment]
Error is
> No SOURCES given to target: ..__nrf__drivers__sensor__bme68x_iaq

**Comment by maxd-nordic** [comment]
@coderbyheart ready to test

**Comment by coderbyheart** [comment]
Wifi crashes:

```
[00:00:02.704,467] <inf> app_event_manager: DATA_EVT_UI_DATA_READY
[00:00:02.709,136] <dbg> modem_module: state_set: State transition STATE_CONNECTING --> STATE_SHUTDOWN
[00:00:02.709,228] <inf> app_event_manager: MODEM_EVT_SHUTDOWN_READY
[00:00:02.709,472] <wrn> modules_common: Module "modem" shutdown registered
[00:00:02.709,503] <dbg> util_module: reboot_ack_check: All modules have ACKed the reboot request.
[00:00:02.709,503] <dbg> util_module: reboot_ack_check: Reboot in 5 seconds.
[00:00:02.825,439] <inf> app_event_manager: UI_EVT_BUTTON_DATA_READY
[00:00:02.825,683] <dbg> cloud_codec_ringbuffer: cloud_codec_populate_ui_buffer: Entry: 2 of 2 in UI buffer filled
[00:00:02.825,744] <inf> app_event_manager: DATA_EVT_UI_DATA_READY
*** Booting nRF Connect SDK  ***dule: Rebooting!
Attempting to boot slot 0.
Attempting to boot from address 0x8200.
Verifying signature against key 0.
Hash: 0x81...ed
Firmware signature verified.
Firmware version 1
*** Booting nRF Connect SDK  ***
*** Booting nRF Connect SDK  ***
[00:00:00.254,730] <err> spi_nor: Device id 00 00 00 does not match config c2 28 17
[00:00:00.257,965] <dbg> watchdog: watchdog_timeout_install: Watchdog timeout installed. Timeout: 60
[00:00:00.257,995] <dbg> watchdog: watchdog_start: Watchdog started
[00:00:00.258,026] <dbg> watchdog: watchdog_feed_enable: Watchdog feed enabled. Timeout: 30000
[00:00:00.258,514] <inf> app_event_manager: APP_EVT_START
[00:00:00.258,605] <dbg> ui_module: state_set: State transition STATE_INIT --> STATE_RUNNING
[00:00:00.258,636] <dbg> ui_module: sub_state_set: Sub state: SUB_STATE_ACTIVE
[00:00:00.258,666] <dbg> ui_module: sub_sub_state_set: Sub state: SUB_SUB_STATE_LOCATION_INACTIVE
```

**Comment by coderbyheart** [comment]
No connection with WiFi (same kit with 1.10.0 works).

**Comment by maxd-nordic** [comment]
I think I finally got it to work. Please test again.

**Comment by coderbyheart** [comment]
WiFi and Solar works

**Pull request merged**
